// <auto-generated />
using System;
using Guesthouse.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Guesthouse.Infrastructure.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20190402172702_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Guesthouse.Core.Domain.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClientRole");

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("Password");

                    b.Property<int>("PayType");

                    b.Property<string>("PhoneNumber");

                    b.HasKey("Id");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("Guesthouse.Core.Domain.Convenience", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<decimal?>("Cost");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Conveniences");
                });

            modelBuilder.Entity("Guesthouse.Core.Domain.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email");

                    b.Property<string>("EmployeeRole");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("Password");

                    b.HasKey("Id");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("Guesthouse.Core.Domain.Invoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("ClientId");

                    b.Property<string>("ClientName");

                    b.Property<string>("CompanyName");

                    b.Property<Guid>("EmployeeId");

                    b.Property<string>("EmployeeName");

                    b.Property<DateTime>("IssueDate");

                    b.Property<decimal>("MoneyToPay");

                    b.Property<DateTime>("PayDate");

                    b.Property<string>("ReservationDescription");

                    b.Property<Guid>("ReservationId");

                    b.HasKey("Id");

                    b.HasIndex("ClientId")
                        .IsUnique();

                    b.HasIndex("EmployeeId")
                        .IsUnique();

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("Guesthouse.Core.Domain.Reservation", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<Guid>("ClientId");

                    b.Property<string>("ClientName");

                    b.Property<string>("Description");

                    b.Property<decimal>("Price");

                    b.HasKey("Id");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("Guesthouse.Core.Domain.Room", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<int>("Floor");

                    b.Property<int>("Number");

                    b.Property<decimal>("Price");

                    b.Property<Guid?>("ReservationId");

                    b.HasKey("Id");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("Guesthouse.Core.Domain.Convenience", b =>
                {
                    b.HasOne("Guesthouse.Core.Domain.Reservation", "Reservation")
                        .WithMany("Conveniences")
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Guesthouse.Core.Domain.Invoice", b =>
                {
                    b.HasOne("Guesthouse.Core.Domain.Client", "Client")
                        .WithOne("Invoice")
                        .HasForeignKey("Guesthouse.Core.Domain.Invoice", "ClientId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Guesthouse.Core.Domain.Employee", "Employee")
                        .WithOne("Invoice")
                        .HasForeignKey("Guesthouse.Core.Domain.Invoice", "EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Guesthouse.Core.Domain.Reservation", b =>
                {
                    b.HasOne("Guesthouse.Core.Domain.Client", "Client")
                        .WithMany("Reservations")
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Guesthouse.Core.Domain.Invoice", "Invoice")
                        .WithMany("Reservations")
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Guesthouse.Core.Domain.Room", b =>
                {
                    b.HasOne("Guesthouse.Core.Domain.Reservation", "Reservation")
                        .WithMany("Rooms")
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
