// <auto-generated />
using System;
using Guesthouse.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Guesthouse.Infrastructure.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20191213211127_Block_to_room_and_convenience")]
    partial class Block_to_room_and_convenience
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Guesthouse.Core.Domain.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClientRole");

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("Password");

                    b.Property<string>("PayType")
                        .IsRequired();

                    b.Property<string>("PhoneNumber");

                    b.Property<Guid?>("ReservationId");

                    b.HasKey("Id");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("Guesthouse.Core.Domain.Convenience", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal?>("Cost");

                    b.Property<bool>("IsBlock");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Conveniences");
                });

            modelBuilder.Entity("Guesthouse.Core.Domain.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email");

                    b.Property<string>("EmployeeRole");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("Password");

                    b.HasKey("Id");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("Guesthouse.Core.Domain.Invoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("ClientId");

                    b.Property<string>("ClientName");

                    b.Property<string>("CompanyName");

                    b.Property<Guid>("EmployeeId");

                    b.Property<string>("EmployeeName");

                    b.Property<DateTime>("IssueDate");

                    b.Property<decimal>("MoneyToPay");

                    b.Property<DateTime>("PayDate");

                    b.Property<string>("ReservationDescription");

                    b.Property<Guid>("ReservationId");

                    b.HasKey("Id");

                    b.HasIndex("ClientId")
                        .IsUnique();

                    b.HasIndex("EmployeeId")
                        .IsUnique();

                    b.HasIndex("ReservationId")
                        .IsUnique();

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("Guesthouse.Core.Domain.Reservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("ClientId");

                    b.Property<string>("ClientName");

                    b.Property<string>("Description");

                    b.Property<DateTime>("EndReservation");

                    b.Property<string>("Message");

                    b.Property<string>("PayStatus")
                        .IsRequired();

                    b.Property<decimal>("Price");

                    b.Property<string>("ReservationStatus")
                        .IsRequired();

                    b.Property<DateTime>("StartReservation");

                    b.HasKey("Id");

                    b.HasIndex("ClientId")
                        .IsUnique()
                        .HasFilter("[ClientId] IS NOT NULL");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("Guesthouse.Core.Domain.ReservationConvenience", b =>
                {
                    b.Property<Guid>("ReservationId");

                    b.Property<Guid>("ConvenienceId");

                    b.Property<decimal?>("Cost");

                    b.HasKey("ReservationId", "ConvenienceId");

                    b.HasIndex("ConvenienceId");

                    b.ToTable("ReservationConveniences");
                });

            modelBuilder.Entity("Guesthouse.Core.Domain.ReservationRoom", b =>
                {
                    b.Property<Guid>("ReservationId");

                    b.Property<Guid>("RoomId");

                    b.Property<DateTime>("BookedAt");

                    b.Property<DateTime>("BookedTo");

                    b.Property<decimal>("Price");

                    b.HasKey("ReservationId", "RoomId");

                    b.HasIndex("RoomId");

                    b.ToTable("ReservationRooms");
                });

            modelBuilder.Entity("Guesthouse.Core.Domain.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Floor");

                    b.Property<bool>("IsBlock");

                    b.Property<int>("Number");

                    b.Property<decimal>("Price");

                    b.HasKey("Id");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("Guesthouse.Core.Domain.Invoice", b =>
                {
                    b.HasOne("Guesthouse.Core.Domain.Client", "Client")
                        .WithOne("Invoice")
                        .HasForeignKey("Guesthouse.Core.Domain.Invoice", "ClientId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Guesthouse.Core.Domain.Employee", "Employee")
                        .WithOne("Invoice")
                        .HasForeignKey("Guesthouse.Core.Domain.Invoice", "EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Guesthouse.Core.Domain.Reservation", "Reservation")
                        .WithOne("Invoice")
                        .HasForeignKey("Guesthouse.Core.Domain.Invoice", "ReservationId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Guesthouse.Core.Domain.Reservation", b =>
                {
                    b.HasOne("Guesthouse.Core.Domain.Client", "Client")
                        .WithOne("Reservation")
                        .HasForeignKey("Guesthouse.Core.Domain.Reservation", "ClientId");
                });

            modelBuilder.Entity("Guesthouse.Core.Domain.ReservationConvenience", b =>
                {
                    b.HasOne("Guesthouse.Core.Domain.Convenience", "Convenience")
                        .WithMany("Reservations")
                        .HasForeignKey("ConvenienceId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Guesthouse.Core.Domain.Reservation", "Reservation")
                        .WithMany("Conveniences")
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Guesthouse.Core.Domain.ReservationRoom", b =>
                {
                    b.HasOne("Guesthouse.Core.Domain.Reservation", "Reservation")
                        .WithMany("Rooms")
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Guesthouse.Core.Domain.Room", "Room")
                        .WithMany("Reservations")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
